Задача 2. Колегов
SoNiceElijah/formal-lang-course pull request #2
Opened 2023-03-05 21:32 UTC by SoNiceElijah

# Задача 2. Построение детерминированного конечного автомата по регулярному выражению и недетерминированного конечного автомата по графу

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/FormalLanguageConstrainedPathQuerying/formal-lang-course/blob/main/tasks/task1.md) (загруженный из набора данных по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

2023-03-06 06:56 UTC, rustam-azimov requested changes

2023-03-06 06:56 UTC, rustam-azimov commented on project/task2.py
> +def build_from_regex(re):
Теперь пишите пожалуйста ко всем функциям докстринги.

2023-03-12 12:26 UTC, SoNiceElijah commented
Прошу прощения, что отправил правки через большой промежуток времени, пропустил сообщение. Добавил докстринги

2023-03-14 12:48 UTC, rustam-azimov approved these changes

2023-03-19 17:09 UTC, merged