Задача 6. Колегов
SoNiceElijah/formal-lang-course pull request #5
Opened 2023-04-08 14:18 UTC by SoNiceElijah

- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html) реализовать **функцию** преобразования контекстно-свободной грамматики в ослабленную нормальную форму Хомского (ОНФХ), но не классическую нормальную форму Хомского (НФХ). НФХ является частным случаем ОНФХ, а значит можно утверждать, что грамматика, находящаяся в НФХ находится и в ОНФХ. Но в данной задаче нас интересует максимально слабая форма, то есть ОНФХ, но не НФХ.
- [x] Предусмотреть возможность чтения грамматики из файла. Формат файла определяется возможностями pyformalng. Например, можно использовать [эту функцию](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html#pyformlang.cfg.CFG.from_text).
- [x] Добавить необходимые тесты.

2023-04-09 09:38 UTC, rustam-azimov requested changes

2023-04-09 09:38 UTC, rustam-azimov commented on project/task6.py
> +            self.remove_useless_symbols()
Лишняя

2023-04-16 19:39 UTC, SoNiceElijah commented
Внес изменения

2023-04-18 09:36 UTC, rustam-azimov approved these changes
2 балла за опоздание

2023-04-22 18:23 UTC, merged